services:
  ai-service:
    container_name: ai-service
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    env_file:
      - ../env_files/ai-service.env
    ports:
      - "6565:6565"
    networks:
      - chain-network

  stock-service:
    container_name: stock-service
    build:
      context: ./stock-service
      dockerfile: Dockerfile
    env_file:
      - ../env_files/stock-service.env
    ports:
      - "8082:8082"
    depends_on:
      - ai-service
    networks:
      - chain-network

networks:
  chain-network:
    driver: bridge