spring:
  application:
    name: stock-service

server:
  port: ${SERVER_PORT}

grpc:
  server:
    proc1:
      address: ${GRPC_SERVER_ADDRESS_1}
      port: ${GRPC_SERVER_PORT_1}
    proc2:
      address: ${GRPC_SERVER_ADDRESS_2}
      port: ${GRPC_SERVER_PORT_2}